language: node_js
node_js:
  - 12
services:
  - mongodb
script: 
  - echo '******Build start******'
  - echo 'Installing Dependencies'
  - npm install
  - echo 'Running tests'
  - mongodb
  - mocha --exit