language: node_js
node_js:
- 12
services:
- mongodb
script:
- echo '******Build start******'
- echo 'Installing Dependencies'
- npm install
- echo 'Running tests'
- mocha --exit
deploy:
  provider: heroku
  api_key:
    secure: C4z2gzil0jBOW0pI5C6NVWd8Ij8qiOct+/m61SxWyVGm9DLQFMFjkHJn/dFzBO87CpCAHalx+yXMZKH4z/q9NtLqCfMC95X9YI9iTRdfkK5T/pQUyCOWtWh8UFHMCrG/7GBkRNSibEKHCZt4uUqCk5d3PKiQDHFN4o99LEfxkmDLzNRKxE+NgzcjfYEK+V/p7RvZ5USg2vdwPEZIomaQYfN/XRJv391bT82VMyLDy+lDG2SGc8BHk5Jq3WtHFWzRB2hbLvv/yesxKNdWw5+VF+ocWw1LmC7xMwfSsSYdvpNZuUJsFGOD5xez0BPkU8ZhH+jqPPTuL0pk09edmGMWnV905OSlOHyVuDFWEhxJ1Ka7LESF3Uj6zKEAUjPIodCZAKXZrD62AabagW40TtnUXdZFOK9bzU7iQYFeXjuT6NoPkNPnQeOf46PCsU2L9rAJ5GZI6fG3xU1xMqD8JZSC+j/yKHb8HGhT5wD8WxSx6YVFAlVwiVe6/n+RL2+9NyoIKYG+1i7i4Y4gKs+9nAX+fKNkb3T9RbCUjQKqpG0iRHe+wWEL1HOI4zT2YeCKxieSLyNnBHTo6sS7wSfvzs5sj7hu1trM5EaPBtAZAuLCKvd8QFR/vZWQsx/3k3xvCIpZl1MFsTSwiQnNsCp3pZhwew0vW5g/vcyfh9/ZHLOdmJY=
  app: pokemon-rest-app
  on:
    repo: shiweing/pokemon-rest-app
